
server:
  port: 8100
  servlet:
    context-path: /mall

spring:
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  typeAliasesPackage: com.shpun.mall.db.model
  mapper-locations: classpath:mapper/**.xml
